### ISSUE TITLE
Ruby 2.2 support for memory and objects

### ISSUE THREAD

**Issue by TheAustinSeven** [ruby-prof/ruby-prof#165]
When running ruby-prof with ruby 2.2.2 I get the following output:
```
    wall_time: 7 ms
    memory: unsupported
    objects: unsupported
    gc_runs: 0
    gc_time: 0 ms
```
I have tried patching with railsexpress with no luck. Either I just haven't figured out how to configure this correctly or support should be added for ruby 2.2.2. Can anyone reproduce?

**Comment by skaes** [comment]
I'd love to help, but without details on how you actually used ruby-prof, it's impossible.

**Comment by TheAustinSeven** [comment]
So I am using ruby-prof with ruby 2.2.2 and rails 4.2, through the 'rails-perftest' gem. I ran the default rails performance test, which is just 'get '/', and I run rake test:benchmark. which produces the output above. I know that the solution in 1.9.3 is to get the gcdata patch, but there is no such patch in 2.2.2. If you need any more information you will have to specify.

**Comment by skaes** [comment]
Thx for providing the link to the rails-perftest gem. It's the first time I came across this gem.

I have checked the ruby-prof implementation: measuring object allocations works perfectly fine in ruby 2.2.2, for memory measurement you will need the railsexpress patches. See https://github.com/skaes/rvm-patchsets.

However, the rails-perftest gem will still not work, because it makes incorrect assumptions about how these measurements have been implemented.

I suggest you create a ticket here: https://github.com/rails/rails-perftest/issues

**Comment by TheAustinSeven** [comment]
Could you please elaborate on what those incorrect assumptions are so that I can pass that information along?

**Comment by skaes** [comment]
Implementation of memory/object/gc runs etc. has changed over time, and will probably continue to change. I suggest the gem authors switch to using the measurement methods provided by ruby-prof (see https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/compatibility.rb).

**Comment by skaes** [comment]
the rails-perftest gem is in a horrible state: is has *only four* unit tests and the only thing they test is number formatting and they don't even run without changing the source code first.

**Comment by TheAustinSeven** [comment]
Thank you!

**Comment by skaes** [comment]
This is not a ruby-prof issue. Closing it.
