### ISSUE TITLE
Visual Studio solution up to date?

### ISSUE THREAD

**Issue by thomthom** [ruby-prof/ruby-prof#226]
I saw there was Visual Studio solution in the repository.

But I'm not able to build it. First I was getting errors about `st_table` being undefined symbol. I found that this was defined in Ruby itself. There are also errors with `gettimeofday` not being defined - because MSVC doesn't offer such function. The docs says that under Windows the extension is using `GetLocalTime` but I'm not seeing any references to that in the project.

I also observer projects for Ruby 1.8, 1.9 and 2.0, but not newer. Is the Visual Studio solution out of date?

**Comment by rdp** [comment]
In essence practically no one uses visual studio builds of Ruby anymore
it's very rare...

On Monday, October 30, 2017, Thomas Thomassen <notifications@github.com>
wrote:
> I saw there was Visual Studio solution in the repository.
>
> But I'm not able to build it. First I was getting errors about st_table
being undefined symbol. I found that this was defined in Ruby itself. There
are also errors with gettimeofday not being defined - because MSVC doesn't
offer such function. The docs says that under Windows the extension is
using GetLocalTime but I'm not seeing any references to that in the project.
>
> I also observer projects for Ruby 1.8, 1.9 and 2.0, but not newer. Is the
Visual Studio solution out of date?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/e_FKU722qkdzTgCcSho_8ppexp6av-EBI_8TUTJd-SayQQ8t-Oyu-ObURDhJAgQaSEuvb5vPOLvC2G55zKJNJ4Qnwyabdb31-Jg0hcLBewRWLnP1WrbbivM1Rs7Pvce-DeRLKTbAmDBYKOGBAR91xopWJSgVKw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0GTvNYqtNYipFkGDmenMKy6Jg1Lxks5sxh9ogaJpZM4QLtIg.gif>

**Comment by thomthom** [comment]
Gotcha. Yea, I have noticed that MSVC builds are a challenge to get working with Ruby. I work with an application that embeds the Ruby interpreter - and for Windows we use MSVC. We've had to make use of the Mingw builds as we never got Ruby working. with MSVC.
