### ISSUE TITLE
Ability to Merge Results

### ISSUE THREAD

**Issue by cfis** [ruby-prof/ruby-prof#271]
It is useful to be able to merge results together, especially when fibers or threads as workers. Currently ruby-prof will show separate results for each fiber (or thread). Combining these calls stacks would make interpretation of results much easier.

See #261, #266

**Comment by ioquatix** [comment]
Can you not just combine the results based on symbolic name, e.g. method name?

**Comment by cfis** [comment]
Yes, that is what I was thinking, as long as the root methods have the same name. It would be nice to do in Ruby, but then the c-api needs to be expanded a fair bit. So maybe I'll just do it C.

**Comment by rmosolgo** [comment]
👋  Long-time listener, first time caller here! Thanks for your work on ruby-prof, it's one of my favorite tools. I'm considering adding Fiber-based concurrency to GraphQL-Ruby (https://github.com/rmosolgo/graphql-ruby/pull/3264) but ran into the issue of results split by fiber. It makes it much harder to interpret the results, since a single GraphQL query is split across several reports. I read that `merge_fibers:` was _previously_ supported, but was removed because of bugs. 

I just thought I'd mention, I'd love to see this if you find time to take a look at it! I'll keep an ear out in the meantime. Thanks again 🍻

**Comment by ioquatix** [comment]
As an alternative, how does stack prof behave?

**Comment by cfis** [comment]
Yes, merge fibers didn't work. Its not actually all the easy to accomplish this which is why it isn't done...But I'll see if I can take another look.

**Comment by cfis** [comment]
@ioquatix this functionality is now available in ruby-prof 1.5.0. Sorry for the long delay.

**Comment by ioquatix** [comment]
Wow that's awesome!!

**Comment by cfis** [comment]
Documented here - https://ruby-prof.github.io/#merge-threads.
