### ISSUE TITLE
profile.merge! is leaving dangling links for merged fibers

### ISSUE THREAD

**Issue by asksurya** [ruby-prof/ruby-prof#320]
Added the below code in the test directory and ran it for reference

```
require 'timeout'
require 'set'
require_relative './scheduler'
require 'bundler/setup'
require 'ruby-prof'

  def worker1
    sleep(0.5)
    puts "worker1"
  end

  def worker2
    b=5+6
    sleep(0.5)
    sleep(0.5)
    puts b
  end

  def worker3
    sleep(0.5)
    puts "worker3"
  end

  def concurrency
    begin 
    scheduler = Scheduler.new
    3.times do |i|
      scheduler.fiber do |a|
        eval("worker#{i+1}")
      end
    end
    scheduler.run
    rescue=>e
       puts e
    end
  end

  result  = RubyProf.profile { concurrency }
  result.merge!
  profilePrinter = RubyProf::MultiPrinter.new(result,[:graph_html,:flat])
  profilePrinter.print(:path => "/tmp/", :profile => "profile_3")

```

This is creating dangling links for the worker 2 and worker 3 in the merged thread
![image](https://user-images.githubusercontent.com/6819025/223866612-ad9c9c2e-788e-4d06-9fb8-b73459a95151.png)

**Comment by cfis** [comment]
Thanks for the report. 

Hmm, I tend to think the bug is that the fibers were deleted in the first place. Each calls a different top level method - worker 1, worker2 and worker3 - thus they cannot be merged (you can see in the results they were not actually merged). For merging to work, the root method in the call stacks need to be the same.

The code is here:

https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/profile.rb#L62

That code is too aggressive. Thread#merge! should return a boolean specifying if it succeeded or not. Where success means the root nodes are the same.

**Comment by asksurya** [comment]
Thanks for the quick reply.

When I tried to comment out the remove threads from 
https://github.com/ruby-prof/ruby-prof/blob/master/lib/ruby-prof/profile.rb#L62

The worker 2 and 3 threads are displayed although the worker 1 thread also displaying 2 and 3 as children of Kernal#eval with dangling pointers.

A couple of observations I found was that the call tree is copying the node as the lead node from other threads when the children don't match, but  
the thread method table is not updated with the new methods from the updated call tree. Also, the children of the node copied are not copied over to the parent thread.
As well as the flat profile is showing a different report from the graph one because the flat one is pulling from the thread->method_table and not the method's call tree.

**Comment by cfis** [comment]
Ok, thanks for digging and the example. Will take a look. Or happy to review a patch if you want to dig in deeper.

**Comment by cfis** [comment]
I took a look at this and my explanation was wrong. But I did figure out what was wrong, and realized the current implementation isn't only a partial solution. So need to find some time and make it better.

**Comment by asksurya** [comment]
I have been working on a fix, its partially done, will update and submit for review once I am done with all the changes.

**Comment by cfis** [comment]
Ok, cool. The current implementation is broken, not sure what I was thinking. I missed an important step. 

To make sure we are on the same page, let me explain the fix I have in mind. This would be written in C.

Each ruby_prof thread has a list of methods (st_table), and a pointer to a root call tree (CallTree).

First merge the methods (this is new code)

  * For methods in thread 2 that are in thread 1, update the thread 1 method time
  * For methods in thread 2 that are not in thread 1, create a new method in thread 1.
 
Every method has a list of call trees associated with it. Do NOT copy these over (because the pointers will back to the thread 2 call trees which would be wrong).

Next, update the merging the call trees code (this part is implemented but needs some changes) so:

* When descending the thread 2 call tree, for each call tree set the method pointer to the right method in thread 1.
* Then check the the method's call trees to see if the current call tree is listed. If yes, update the call tree time. If no, then add it
*  When merging the call trees, the current code updates the method time. That would now be wrong, and result in a double count (since the method times were combined in the step discussed above).

Let me know if you have any questions. Note I have created a separate test file for merge tests, including the one you posted above. I will check that in.

**Comment by cfis** [comment]
@asksurya thanks for pushing this forward. I made a bunch of changes to your PR and have merged it into master. So hopefully this is now fixed.
